Repository ITYL-Bbbbick/beBig_front, pull requests merged in 2024-10, with the labels that each got.

#45 Bebig 165 mypage form
  src/api/MypageApi.js
  src/components/Footer.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/router/mypage.js
Labels: feat

#50 Bebig 70 mypage edit
  public/images/badge/badge0.png
  public/images/badge/badge1.png
  public/images/badge/badge2.png
  public/images/badge/badge3.png
  src/api/MypageApi.js
  src/pages/home/Main.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/router/mypage.js
Labels: feat

#54 [BEBIG-165] feat : 마이페이지 뱃지 설명 모달창 연결
  src/api/MypageApi.js
  src/pages/mypage/Mypage.vue
Labels: feat

#62 [BEBIG-188] feat : 마이페이지 공개/비공개 기능
  package-lock.json
  public/images/badge/badge0.png
  public/images/badge/badge1.png
  public/images/badge/badge2.png
  public/images/badge/badge3.png
  src/App.vue
  src/api/MypageApi.js
  src/assets/main.css
  src/components/Header.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  tailwind.config.js
Labels: feat

#64 [BEBIG-194] feat : 커뮤니티 프로필 연결 미완성
  src/api/CommunityApi.js
  src/pages/community/CommunityList.vue
  src/router/mypage.js
Labels: feat

#70 Bebig 196 community profile mypage connect
  src/api/MypageApi.js
  src/components/Footer.vue
  src/pages/community/CommunityList.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/router/mypage.js
Labels: feat

#76 [BEBIG-69] feat : 마이페이지 작성한 글/좋아요한 글 게시글로 연결
  src/pages/mission/Mission.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/router/mypage.js
Labels: feat

#80 [BEBIG-213] feat : 로그인,아이디찾기, 비번찾기 웹css 완성
  src/App.vue
  src/assets/main.css
  src/pages/user/FindID.vue
  src/pages/user/FindPwd.vue
  src/pages/user/Login.vue
Labels: feat

#85 [BEBIG-213] feat : 로그인, 회원가입, 아이디/비번 찾기 페이지 웹css 완성
  src/App.vue
  src/assets/main.css
  src/pages/user/FindID.vue
  src/pages/user/FindPwd.vue
  src/pages/user/Login.vue
  src/pages/user/Signup.vue
  src/pages/user/SocialSignup.vue
  src/pages/user/TermsModal.vue
Labels: feat

#86 [BEBIG-222] feat : main 화면 웹,모바일CSS
  src/App.vue
  src/assets/main.css
  src/components/Footer.vue
  src/components/Header.vue
  src/components/WebHeader.vue
  src/pages/home/AccountList.vue
  src/pages/home/AddBank.vue
  src/pages/home/BankLogin.vue
  src/pages/home/Main.vue
  src/pages/home/SurveyResult.vue
  src/pages/mypage/Mypage.vue
Labels: feat

#89 [BEBIG-229] feat : 웹 헤더 기능 추가
  src/components/WebHeader.vue
Labels: feat

#93 [BEBIG-223] feat : 계좌목록 css
  src/assets/main.css
  src/pages/home/AccountDetail.vue
  src/pages/home/AccountList.vue
  src/pages/home/AddBank.vue
  src/pages/home/BankLogin.vue
  src/pages/home/Main.vue
  src/pages/home/Survey.vue
  src/pages/home/SurveyStart.vue
Labels: feat

#98 [Bebig 232] 웹페이지 반응형 커뮤니티 페이지
  src/pages/community/CommunityList.vue
Labels: feat

#99 [BEBIG-223] chore : 계좌 연결 시 로고 연결
  src/pages/home/BankLogin.vue
Labels: chore

#104 bebig-254 feat : 총 자산 분석 기타 자산 추가
  src/pages/asset/Asset.vue
Labels: feat

#113 bebig-247 debug : 월간 미션 완료 시 텍스트 줄 수정
  src/pages/home/Main.vue
  src/pages/mission/Mission.vue
Labels: bug

#115 [BEBIG-241] feat : 비번 정규표현식 추가, 계좌연결 없을때 마이페이지에서 달성도 그래프 숨기기
  src/assets/main.css
  src/pages/home/Main.vue
  src/pages/mypage/Mypage.vue
  src/pages/user/Signup.vue
Labels: feat, chore

#116 [BEBIG-264] feat : 순위->비율, 자산표현
  src/pages/asset/Asset.vue
Labels: feat

#119 bebig-265 feat : 비회원 게시글 상세보기 경고창 수정
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityList.vue
Labels: feat

#121 [BEBIG-225] feat : 거래내역 인피니티스크롤
  src/api/HomeApi.js
  src/pages/home/AccountDetail.vue
Labels: feat

#126 [BEBIG-268] chore : input태크 선택시 확대 방지, 주소 공유시 설정
  index.html
Labels: chore

#127 bebig-269 chore : 게시글 상세화면 css 수정
  src/pages/community/CommunityDetail.vue
Labels: chore

#133 [BEBIG-269] chore : 사진수정, 마이페이지/커뮤니티 오류수정
  images/1-face.png
  images/2-face.png
  images/3-face.png
  src/assets/main.css
  src/pages/community/CommunityList.vue
  src/pages/mypage/Mypage.vue
  tailwind.config.js
Labels: chore

#135 [BEBIG-276]-자산분석 웹CSS
  src/assets/main.css
  src/components/Header.vue
  src/components/WebHeader.vue
  src/pages/asset/Asset.vue
  src/pages/community/CommunityAdd.vue
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityList.vue
  src/pages/mypage/Mypage.vue
  src/pages/user/FindPwd.vue
  src/pages/user/Login.vue
Labels: feat, chore

#136 Release/1.7.0
  images/1-face.png
  images/2-face.png
  images/3-face.png
  src/api/HomeApi.js
  src/assets/main.css
  src/components/Header.vue
  src/components/WebHeader.vue
  src/pages/asset/Asset.vue
  src/pages/community/CommunityAdd.vue
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityList.vue
  src/pages/home/AccountDetail.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/pages/user/FindPwd.vue
  src/pages/user/Login.vue
  tailwind.config.js
Labels: deploy

#138 [BEBIG-222] chore : 여러가지 수정
  src/assets/main.css
  src/pages/asset/Asset.vue
  src/pages/home/Main.vue
  src/pages/home/Survey.vue
  src/pages/home/SurveyResult.vue
  src/pages/home/SurveyStart.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
Labels: chore

#157 Release/1.8.0
  images/4-face.png
  public/images/bank/loading.gif
  src/api/HomeApi.js
  src/assets/main.css
  src/components/Footer.vue
  src/components/WebHeader.vue
  src/pages/asset/Asset.vue
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityList.vue
  src/pages/home/AccountList.vue
  src/pages/home/AddBank.vue
  src/pages/home/BankLogin.vue
  src/pages/home/Main.vue
  src/pages/home/Survey.vue
  src/pages/home/SurveyResult.vue
  src/pages/home/SurveyStart.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/pages/user/FindID.vue
  src/pages/user/Signup.vue
Labels: deploy

#161 [BEBIG-305] chore : 미션페이지 css재설정
  src/assets/main.css
  src/components/Footer.vue
  src/pages/asset/Asset.vue
  src/pages/home/Main.vue
  src/pages/mission/Mission.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
Labels: chore

#168 [BEBIG-307] chore : 유형검사 CSS수정
  src/assets/main.css
  src/pages/home/Survey.vue
Labels: chore

#169 [chore] : favicon 수정
  index.html
  public/favicon.ico
Labels: chore

#170 Release/1.10.0
  images/kakao_login_btn.png
  images/symbol.png
  index.html
  public/favicon.ico
  src/App.vue
  src/assets/main.css
  src/components/Footer.vue
  src/pages/asset/Asset.vue
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityList.vue
  src/pages/home/AccountDetail.vue
  src/pages/home/AddBank.vue
  src/pages/home/BankLogin.vue
  src/pages/home/Main.vue
  src/pages/home/Survey.vue
  src/pages/mission/Mission.vue
  src/pages/mypage/Mypage.vue
  src/pages/mypage/MypageEdit.vue
  src/pages/mypage/MypageSocialEdit.vue
  src/pages/user/Login.vue
  src/stores/footerStore.js
Labels: deploy

#171 [BEBIG-305] chore : 유형검사 수정 찐막
  src/assets/main.css
  src/pages/home/Survey.vue
  src/pages/home/SurveyStart.vue
Labels: chore

#172 Release/1.10.1
  src/assets/main.css
  src/pages/home/Survey.vue
  src/pages/home/SurveyStart.vue
Labels: deploy

#173 [BEBIG-310] chore : 자잘한 오류 수정
  src/assets/main.css
  src/pages/asset/Asset.vue
  src/pages/home/AccountDetail.vue
  src/pages/home/AccountList.vue
  src/pages/home/AddBank.vue
  src/pages/home/BankLogin.vue
  src/pages/mission/Mission.vue
Labels: chore
